# `version` top level element obsolete in 1.27.4 (https://docs.docker.com/reference/compose-file/version-and-name/)
# version: "3.3"

# `name` top level element should work according to above link, but it is throwing a conflicting error saying that there needs to be a version,
# but if the version is present, it ignores it. Commenting out the name and allows the `make run` command to work. This might be an issue of
# using the Ubuntu OS instead of a iOS or Windows OS. Keeping the local like this to proceed, would reach out and discuss with whoever set up
# at a latter time to see if there is a better resolution.
# name: investifi-backend-coding-challenge

services:
  investifi-backend-coding-challenge:
    container_name: investifi-backend-coding-challenge
    build:
      context: ../..
      dockerfile: docker/config/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ../../src:/app/src
      - ../../docker:/app/docker
      - ../../test:/app/test
    depends_on: 
      - db
    env_file:
      - ../env/.env

  db:
    image: amazon/dynamodb-local
    container_name: db
    command: "-jar DynamoDBLocal.jar -port 8003 -sharedDb -optimizeDbBeforeStartup -dbPath /home/dynamodblocal/data/"
    ports:
      - 8003:8003
    user: root
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

  db-admin:
    container_name: db-admin
    build:
      context: .
      dockerfile: db-admin.Dockerfile
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://db:8003
    depends_on:
      - db

volumes:
  dynamodb_data: null